package targets

import "strings"

// generateAgentsMD creates a comprehensive AGENTS.md file for OpenAI Codex CLI.
func generateAgentsMD() []byte {
	content := strings.Join([]string{
		"# OpenKit - Agents Configuration",
		"",
		"This project uses OpenKit for Spec-Driven Development (SDD).",
		"",
		"## What is OpenKit?",
		"",
		"OpenKit is a universal toolkit that provides:",
		"",
		"- **SDD Workflow** - Structured approach: specify, clarify, plan, implement, test",
		"- **Skills** - Reusable patterns for clean code, testing, API design, security",
		"- **Rules** - Command policies for safe automation",
		"- **Commands** - Shortcuts for common development tasks",
		"",
		"## SDD Workflow Commands",
		"",
		"Use these commands in order for Spec-Driven Development:",
		"",
		"| Phase | Command | Purpose | Output |",
		"|-------|---------|---------|--------|",
		"| 0 | `/context` | Discovery - analyze codebase | `docs/.context/` |",
		"| 1 | `/specify <feature>` | Create feature specification | `docs/requirements/<feature>/` |",
		"| 1 | `/clarify` | Resolve ambiguities | Updates spec files |",
		"| 2 | `/plan <feature>` | Create implementation plan | `PLAN.md` |",
		"| 3 | `/tasks` | Generate task breakdown | `docs/sprint/Sprint-XX/TASKS.md` |",
		"| 4 | `/impl` | Execute implementation | Code changes |",
		"| 5 | `/test` | Run verification | Test results |",
		"| 5 | `/checklist` | Pre-commit validation | Pass/fail report |",
		"",
		"## Quick Start",
		"",
		"1. Run `/context` to understand the codebase",
		"2. Run `/specify <feature>` to create a spec",
		"3. Run `/clarify` to resolve any ambiguities",
		"4. Run `/plan <feature>` after spec is complete",
		"5. Run `/tasks` to generate task breakdown",
		"6. Run `/impl` to start coding (follows TASKS.md)",
		"7. Run `/checklist` before committing",
		"",
		"## Project Structure",
		"",
		"```",
		"docs/",
		"  requirements/         # Feature specifications",
		"    <feature>/",
		"      PROBLEM_STATEMENT.md",
		"      USER_STORIES.md",
		"      ACCEPTANCE_CRITERIA.md",
		"      RISKS.md",
		"      PLAN.md",
		"  sprint/               # Sprint planning",
		"    Sprint-XX/",
		"      SPRINT_GOAL.md",
		"      BACKLOG.md",
		"      TASKS.md",
		"",
		".agents/",
		"  skills/               # Reusable development skills",
		"",
		".codex/",
		"  rules/                # Command execution policies",
		"```",
		"",
		"## SDD Workflow Details",
		"",
		"Before writing code, follow this process:",
		"",
		"### Phase 0: Discovery (/context)",
		"",
		"Analyze the codebase to understand:",
		"- Project structure and architecture",
		"- Existing patterns and conventions",
		"- Dependencies and integrations",
		"",
		"### Phase 1: Specification (/specify, /clarify)",
		"",
		"Create a feature spec in `docs/requirements/<feature>/`:",
		"",
		"- **PROBLEM_STATEMENT.md** - What problem are we solving?",
		"- **USER_STORIES.md** - Who benefits and how?",
		"- **ACCEPTANCE_CRITERIA.md** - How do we verify success?",
		"- **RISKS.md** - What could go wrong?",
		"",
		"Then resolve ambiguities with `/clarify`:",
		"",
		"- Edge cases",
		"- Performance requirements",
		"- Security considerations",
		"- Backward compatibility",
		"",
		"### Phase 2: Planning (/plan)",
		"",
		"Create `PLAN.md` with:",
		"",
		"- Implementation approach",
		"- Phase breakdown",
		"- Verification steps",
		"",
		"### Phase 3: Task Breakdown (/tasks)",
		"",
		"Generate task list in `docs/sprint/Sprint-XX/TASKS.md`:",
		"",
		"- Each task has INPUT, OUTPUT, VERIFY",
		"- Tasks are ordered by dependency",
		"- Mark complete as you go",
		"",
		"### Phase 4: Implementation (/impl)",
		"",
		"Execute tasks with discipline:",
		"",
		"- Read the spec before coding",
		"- Run verification after each task",
		"- Update docs if behavior changes",
		"",
		"### Phase 5: Verification (/test, /checklist)",
		"",
		"Verify the implementation:",
		"",
		"- Unit tests for business logic",
		"- Integration tests for workflows",
		"- Manual testing of edge cases",
		"",
		"## Skills Reference",
		"",
		"Consult `.agents/skills/` for detailed guidance:",
		"",
		"### Core Skills",
		"",
		"- `clean-code/` - Code quality patterns (SOLID, DRY, KISS)",
		"- `testing-patterns/` - Unit, integration, E2E strategies",
		"- `tdd-workflow/` - Test-Driven Development process",
		"",
		"### Architecture & Design",
		"",
		"- `api-patterns/` - RESTful design, versioning, pagination",
		"- `database-design/` - Schema, indexing, migrations",
		"- `architecture/` - System design decisions",
		"",
		"### Security & Quality",
		"",
		"- `vulnerability-scanner/` - OWASP Top 10, supply chain",
		"- `security-auditor/` - Authentication, authorization",
		"",
		"### Frontend & Mobile",
		"",
		"- `frontend-design/` - UI/UX principles",
		"- `tailwind-patterns/` - Modern CSS patterns",
		"- `mobile-design/` - Touch interfaces, performance",
		"",
		"### DevOps & Deployment",
		"",
		"- `deployment-procedures/` - Safe deployment workflows",
		"- `server-management/` - Process management, monitoring",
		"",
		"## Command Policies",
		"",
		"This project uses `.codex/rules/` to control command execution.",
		"",
		"See `.codex/rules/openkit.rules` for pre-approved commands.",
		"",
		"## Working Agreements",
		"",
		"### Code Quality",
		"",
		"- Functions < 20 lines when possible",
		"- Max 3 parameters per function",
		"- Descriptive names, avoid abbreviations",
		"- No magic numbers, use constants",
		"",
		"### Testing",
		"",
		"- Write tests before fixing bugs",
		"- Aim for 80%+ code coverage",
		"- Test edge cases and error paths",
		"",
		"### Security",
		"",
		"- Never commit secrets or API keys",
		"- Validate all user inputs",
		"- Use parameterized queries",
		"- Follow principle of least privilege",
		"",
		"### Git",
		"",
		"- Commit messages: `feat|fix|docs|test|refactor|perf|chore: description`",
		"- Branch names: `feat/<area>-<slug>`",
		"- Review changes before committing",
		"",
		"## Verification Scripts",
		"",
		"Before committing, run:",
		"",
		"```bash",
		"# Lint and type check",
		"npm run lint",
		"npm run type-check",
		"",
		"# Run tests",
		"npm test",
		"",
		"# Build verification",
		"npm run build",
		"```",
		"",
		"## Documentation",
		"",
		"Keep these files updated:",
		"",
		"- `README.md` - Project overview",
		"- `docs/requirements/` - Feature specs",
		"- `docs/sprint/` - Sprint progress",
		"- Inline comments for complex logic",
		"",
		"## Getting Help",
		"",
		"- Read the spec in `docs/requirements/<feature>/`",
		"- Check the plan in `PLAN.md`",
		"- Review risks in `RISKS.md`",
		"- Consult skills in `.agents/skills/`",
		"",
	}, "\n")
	return []byte(content)
}

// generateCodexRules creates a Starlark rules file for Codex CLI.
func generateCodexRules() []byte {
	content := strings.Join([]string{
		"# OpenKit Command Policies",
		"#",
		"# This file defines which commands Codex can run outside the sandbox.",
		"# Uses Starlark syntax with prefix_rule() for pattern matching.",
		"",
		"# Safe read-only git commands",
		"prefix_rule(",
		"    pattern = [\"git\", \"status\"],",
		"    decision = \"allow\",",
		"    justification = \"Read-only git status is safe\",",
		"    match = [",
		"        \"git status\",",
		"        \"git status --short\",",
		"    ],",
		")",
		"",
		"prefix_rule(",
		"    pattern = [\"git\", \"log\"],",
		"    decision = \"allow\",",
		"    justification = \"Reading git history is safe\",",
		"    match = [",
		"        \"git log\",",
		"        \"git log --oneline\",",
		"        \"git log -n 10\",",
		"    ],",
		")",
		"",
		"prefix_rule(",
		"    pattern = [\"git\", \"diff\"],",
		"    decision = \"allow\",",
		"    justification = \"Reading diffs is safe\",",
		"    match = [",
		"        \"git diff\",",
		"        \"git diff HEAD\",",
		"        \"git diff --cached\",",
		"    ],",
		")",
		"",
		"# Package manager read operations",
		"prefix_rule(",
		"    pattern = [\"npm\", \"list\"],",
		"    decision = \"allow\",",
		"    justification = \"Listing packages is safe\",",
		")",
		"",
		"prefix_rule(",
		"    pattern = [\"npm\", \"outdated\"],",
		"    decision = \"allow\",",
		"    justification = \"Checking outdated packages is safe\",",
		")",
		"",
		"# Test and build commands (prompt before running)",
		"prefix_rule(",
		"    pattern = [\"npm\", \"test\"],",
		"    decision = \"prompt\",",
		"    justification = \"Tests should run with approval\",",
		")",
		"",
		"prefix_rule(",
		"    pattern = [\"npm\", \"run\", \"build\"],",
		"    decision = \"prompt\",",
		"    justification = \"Build should run with approval\",",
		")",
		"",
		"prefix_rule(",
		"    pattern = [\"npm\", \"run\", \"lint\"],",
		"    decision = \"allow\",",
		"    justification = \"Linting is safe\",",
		")",
		"",
		"# Forbidden destructive operations",
		"prefix_rule(",
		"    pattern = [\"rm\", \"-rf\"],",
		"    decision = \"forbidden\",",
		"    justification = \"Recursive deletion is dangerous. Use file tools instead.\",",
		")",
		"",
		"prefix_rule(",
		"    pattern = [\"git\", \"push\", \"--force\"],",
		"    decision = \"forbidden\",",
		"    justification = \"Force push can lose history. Use regular push.\",",
		")",
		"",
	}, "\n")
	return []byte(content)
}
