package targets

import "strings"

// generateCursorRules creates enhanced .cursorrules content for Cursor IDE.
func generateCursorRules() []byte {
	content := strings.Join([]string{
		"# Cursor Rules - OpenKit",
		"",
		"This project uses OpenKit for Spec-Driven Development.",
		"",
		"## SDD Workflow Commands",
		"",
		"Use these commands in order for Spec-Driven Development:",
		"",
		"| Phase | Command | Purpose |",
		"|-------|---------|---------|",
		"| 0 | `/context` | Discovery - analyze codebase |",
		"| 1 | `/specify <feature>` | Create feature specification |",
		"| 1 | `/clarify` | Resolve ambiguities |",
		"| 2 | `/plan <feature>` | Create implementation plan |",
		"| 3 | `/tasks` | Generate task breakdown |",
		"| 4 | `/impl` | Execute implementation |",
		"| 5 | `/test` | Run verification |",
		"| 5 | `/checklist` | Pre-commit validation |",
		"",
		"## Quick Start",
		"",
		"1. Run `/context` to understand the codebase",
		"2. Run `/specify <feature>` to create a spec",
		"3. Run `/plan <feature>` after spec is complete",
		"4. Run `/impl` to start coding",
		"",
		"## Core Principles",
		"",
		"- Follow the SDD workflow before making changes",
		"- Always read docs/requirements/ before coding",
		"- Document decisions in docs/sprint/Sprint-XX/",
		"- Run verification scripts before committing",
		"",
		"## Project Structure",
		"",
		"- `docs/requirements/` - Feature specifications",
		"- `docs/sprint/` - Sprint planning and tasks",
		"- `.cursor/rules/` - Modular rules (see openkit.mdc)",
		"- `.cursor/skills/` - Reusable skills and patterns",
		"",
		"## Verification Commands",
		"",
		"Run these before finalizing work:",
		"",
		"```bash",
		"# Run linters and type checks",
		"npm run lint",
		"",
		"# Run test suite",
		"npm test",
		"",
		"# Verify full build",
		"npm run build",
		"```",
		"",
		"## Skills",
		"",
		"Reference skills in `.cursor/skills/` for guidance on:",
		"- Clean code patterns",
		"- Testing strategies",
		"- API design",
		"- Security best practices",
		"",
		"For detailed rules, see `.cursor/rules/openkit.mdc`.",
		"",
	}, "\n")
	return []byte(content)
}

// generateCursorMDC creates a modular rule file for Cursor's .cursor/rules/ directory.
func generateCursorMDC() []byte {
	content := strings.Join([]string{
		"---",
		"name: OpenKit SDD Rules",
		"description: Spec-Driven Development workflow for OpenKit projects",
		"---",
		"",
		"# OpenKit SDD Rules",
		"",
		"## SDD Workflow Commands",
		"",
		"Use these commands in order for Spec-Driven Development:",
		"",
		"| Phase | Command | Purpose | Output |",
		"|-------|---------|---------|--------|",
		"| 0 | `/context` | Discovery - analyze codebase | `docs/.context/` |",
		"| 1 | `/specify <feature>` | Create feature specification | `docs/requirements/<feature>/` |",
		"| 1 | `/clarify` | Resolve ambiguities | Updates spec files |",
		"| 2 | `/plan <feature>` | Create implementation plan | `PLAN.md` |",
		"| 3 | `/tasks` | Generate task breakdown | `docs/sprint/Sprint-XX/TASKS.md` |",
		"| 4 | `/impl` | Execute implementation | Code changes |",
		"| 5 | `/test` | Run verification | Test results |",
		"| 5 | `/checklist` | Pre-commit validation | Pass/fail report |",
		"",
		"## Quick Start",
		"",
		"1. `/context` - Understand the codebase",
		"2. `/specify <feature>` - Create a spec",
		"3. `/clarify` - Resolve ambiguities",
		"4. `/plan <feature>` - Create implementation plan",
		"5. `/tasks` - Generate task breakdown",
		"6. `/impl` - Start coding",
		"7. `/checklist` - Validate before commit",
		"",
		"## Workflow Overview",
		"",
		"This project follows Spec-Driven Development (SDD):",
		"",
		"1. **Phase 0: Discovery** - Run `/context` to analyze codebase",
		"2. **Phase 1: Specification** - Run `/specify` then `/clarify`",
		"3. **Phase 2: Planning** - Run `/plan` to create implementation plan",
		"4. **Phase 3: Task Breakdown** - Run `/tasks` to generate TASKS.md",
		"5. **Phase 4: Implementation** - Run `/impl` to execute tasks",
		"6. **Phase 5: Verification** - Run `/test` and `/checklist`",
		"",
		"## Before Writing Code",
		"",
		"- Run `/context` to understand the codebase",
		"- Check if a spec exists in `docs/requirements/`",
		"- If missing, run `/specify <feature>` then `/clarify`",
		"- Review RISKS.md for known issues",
		"- Read PLAN.md for implementation approach",
		"",
		"## During Implementation",
		"",
		"- Follow the task list in `docs/sprint/Sprint-XX/TASKS.md`",
		"- Mark tasks complete as you go",
		"- Run verification commands after each task",
		"- Update docs if behavior changes",
		"",
		"## Code Quality Standards",
		"",
		"### General",
		"",
		"- Functions should be < 20 lines when possible",
		"- Use descriptive names, avoid abbreviations",
		"- Prefer composition over inheritance",
		"- Write unit tests for business logic",
		"",
		"### Security",
		"",
		"- Never commit secrets or API keys",
		"- Validate all user inputs",
		"- Use parameterized queries for databases",
		"- Follow OWASP Top 10 guidelines",
		"",
		"### Testing",
		"",
		"- Write tests before fixing bugs (TDD for bug fixes)",
		"- Aim for 80%+ code coverage",
		"- Test edge cases and error conditions",
		"- Use descriptive test names",
		"",
		"## Verification Scripts",
		"",
		"Before committing, run:",
		"",
		"```bash",
		"# Lint check",
		"npm run lint",
		"",
		"# Type check",
		"npm run type-check",
		"",
		"# Run tests",
		"npm test",
		"",
		"# Build verification",
		"npm run build",
		"```",
		"",
		"## Skills Reference",
		"",
		"Consult `.cursor/skills/` for detailed guidance:",
		"",
		"- `clean-code/` - Code quality patterns",
		"- `testing-patterns/` - Test strategies",
		"- `api-patterns/` - API design principles",
		"- `database-design/` - Schema best practices",
		"- `security-fundamentals/` - Security guidelines",
		"",
		"## Documentation",
		"",
		"Keep these updated:",
		"",
		"- `docs/requirements/<feature>/` - Feature specs",
		"- `docs/sprint/Sprint-XX/TASKS.md` - Task progress",
		"- `README.md` - High-level overview",
		"- Inline code comments for complex logic",
		"",
	}, "\n")
	return []byte(content)
}
