version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: openkit
    main: ./cmd/openkit
    binary: openkit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: openkit
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: orionlabz
    name: openkit
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"

# Homebrew tap disabled for now
# brews:
#   - name: openkit
#     repository:
#       owner: openkit-devtools
#       name: homebrew-tap
#     homepage: https://openkit.dev
#     description: Universal Spec-Driven Development toolkit for AI coding agents
#     license: MIT
#     test: |
#       system "#{bin}/openkit --version"
#     install: |
#       bin.install "openkit"
